### ISSUE TITLE
PSXTAL-3FO - Onboard clock decoupling question

### ISSUE THREAD

**Issue by TheFellowJasper** [L10N37/PSXTAL#3]
Hello, after reading on how to get my PU-22 psx dual-region capable, i've stumbled upon your project and immediately became interested. I have one question however, since I assume its required step, how did you decouple internal console clock? From the install picutre I've seen you've desoldered IC204, but what about the rest? Not exactly sure where to trace other passive elements (as in, to which pins of the gpu are they connected)

**Comment by TheFellowJasper** [comment]
Ok, I think I've found pins I need. 196/192 and 199 should be the pins I need to trace signals from, is this correct?

**Comment by L10N37** [comment]
Hi there, sorry for the late response.  Just got these emails now.

I left a diagram showing that I removed the entire PLL providing all 3 clocks and replaced them with my project. it shows you where you wire each signal /clock back into the board.

If you only want to get the accurate refresh rate from scalers you don't need to go to this extent and can simply wire in the NTSC Oscillator (large one) onto the VCKN-A pin after separating the trace from the other VCKP-A pin (cut trace or pin lift)

**Comment by TheFellowJasper** [comment]
Sorry for ghosting my own issue, life things and all that

Just wanted to report that your mod seems to be working well on my PSX, big thanks for making this mod :)

**Comment by L10N37** [comment]
No worries :)
I'm in the process of making a stand-alone one on a custom PCB starting with just the GPU clock, but I haven't got much spare time lately.
Trying to get it working without an external XTAL (for the MCU) is where it's at..

Thanks for the feedback :)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
